### PR TITLE
support to Apache POI 3.11 and new test case

### PR DESCRIPTION
**Pull request by sw360cab**
I just tried to: 
- Import the project.
- Compile & Run Tests. (Success)
- Switched Apache POI to v. 3.11. (Success)
- Add test case to the existing suite using feature that are peculiar of Apache POI 3.11. (Success)
- Run all the test suite against Apache POI 3.11. (Success)

### CODE REVIEW

**Comment by sw360cab** [comment]
Great!

**Comment by jakubnabrdalik** [comment]
Thank you for updating it.
Now just a sec, I still need to publish the plugin :)

**Comment by sw360cab** [comment]
Yes you are are right! 
Just as soon as I wrote, I realized we were still missing a step

**Comment by sw360cab** [comment]
in terms of distribution via repositories, will you update v. 0.2.1 or switch to 0.2.2?

**Comment by jakubnabrdalik** [comment]
0.2.2.
One should never "update" published jars, unless those are snapshots.

**Comment by sw360cab** [comment]
That's correct. I was wondering that since the plugin branch still as 0.2.1.
Ok I'll wait the new version publication to upgrade my projects conf.
Cheers

**Comment by sw360cab** [comment]
well I have just downloaded that. It works smootly. Thanks again, you can even close the related issue #23, I think..

**Pull request merged**
